name: Deploy Static Pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [main]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: yarn

      - run: yarn install --immutable
      - run: yarn web

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v2
        with:
          path: "out/web"

      - uses: actions/deploy-pages@v2
        id: deployment
